# Generated by Django 5.1.2 on 2024-11-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe_preparation_time_cookingstep_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question'),
        ),
        migrations.AlterField(
            model_name='cookingstep',
            name='recipeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
